apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ lower .Values.name }}
  template:
    metadata:
      labels:
        app: {{ lower .Values.name }}
    spec:
      containers:
      - name: {{ lower .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        {{- include "synkronized.pod.resources" . | nindent 8 }}
        env:
        {{- range $k, $v := .Values.vaultSecrets }}
        - name: {{$k}}
          valueFrom:
            secretKeyRef:
              name: {{lower $k | replace "_" "-"}}
              key: value
        {{- end}}
        {{- range $k, $v := .Values.env }}
        - name: {{$k}}
          value: {{$v}}
        {{- end}}
        