apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ lower .Values.name }}
  template:
    metadata:
      labels:
        app: {{ lower .Values.name }}
    spec:
      containers:
      - name: {{ lower .Values.name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        {{- include "synkronized.pod.resources" . | nindent 8 -}}
        {{ if .Values.gateway }}
        ports:
        - containerPort: {{ .Values.gateway.containerPort }}
        {{- end }}
        {{- if .Values.env }}
        env:
        {{- range $v := .Values.vaultSecrets }}
        - name: {{$v.name}}
          valueFrom:
            secretKeyRef:
              name: {{lower $v.name | replace "_" "-"}}
              key: value
        {{- end}}
        {{- range $v := .Values.env }}
        - name: {{$v.name}}
          value: {{$v.value}}
        {{- end -}}
        {{- end}}