{{ if .Values.gateway }}
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
spec:
  selector:
    app: {{ lower .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.gateway.containerPort }}
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-gateway
  {{- if not .Values.gateway.public }}
  annotations:
    cert-manager.io/cluster-issuer: local-issuer
  {{- end }}
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: {{ .Values.gateway.hostname }}
  listeners:
  - protocol: HTTP
    hostname: {{ .Values.gateway.hostname }}
    port: 80
    name: http
  {{ if not .Values.gateway.public }}
  - protocol: HTTPS
    hostname: {{ .Values.gateway.hostname }}
    port: 443
    name: https
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: secret-tls-https-local
  {{ end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-route
spec:
  parentRefs:
  - name: http-gateway
    namespace: {{ lower .Values.name }}
  hostnames:
  - {{ .Values.gateway.hostname | quote}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: cluster-ip
      port: 80
---
{{ if not .Values.gateway.public }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: local-https-redirect
spec:
  parentRefs:
  - name: gateway
    sectionName: http
    namespace: {{ lower .Values.name }}
  hostnames:
  - {{ .Values.gateway.hostname }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{ end }}

{{ end }}