{{- range $k, $v := .Values.vaultSecrets -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-{{lower $k | replace "_" "-"}}
spec:
  type: kv-v2
  mount: kv
  path: {{$v}}
  destination:
    name: {{lower $k | replace "_" "-"}}
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-static-auth
{{- end}}